# Generated by Django 2.1.3 on 2018-12-07 08:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mycontact', '0002_mycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menuName', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('menuCal', models.CharField(max_length=200)),
                ('menuPrice', models.CharField(max_length=200)),
                ('menuImg', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeName', models.CharField(max_length=200)),
                ('noticeContent', models.CharField(max_length=2000)),
                ('noticeCount', models.IntegerField()),
                ('noticeTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.IntegerField(primary_key=True, serialize=False)),
                ('isDone', models.BooleanField()),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('menuId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycontact.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seatNo', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('isFull', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('userPw', models.CharField(max_length=200)),
                ('userName', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mycontact',
            name='author',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='myContact',
        ),
        migrations.AddField(
            model_name='order',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycontact.User'),
        ),
        migrations.AddField(
            model_name='notice',
            name='noticeWriter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycontact.User'),
        ),
    ]
